name: 3rd party API

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir .pip-cache -r requirements.txt

      - name: Lint code
        run: flake8

      - name: Run Tests
        if: always()
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Check Tests Status
        if: ${{ steps.test.outcome == 'failure' }}
        run: exit 1

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          repository: ${{ github.repository }}
          path: gh-pages

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
